# Generated by Django 4.2.16 on 2024-09-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_person_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
